services:
  - type: web
    name: ghost-cell-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8958912849:AAE4LQG6QlA3qGQccfIbI8ghZDMgWida-yg
      - key: TELEGRAM_CHAT
        value: "972326806"
      - key: PORT
        value: "3000"
